FROM python:3.11-bullseye

ARG WORKSPACE

# WORKDIR ${WORKSPACE}/ecco
# RUN apk add gcc clang lld musl-dev compiler-rt libffi-dev
# RUN pip install poetry
# ADD . ${WORKSPACE}/ecco

# RUN poetry install

# ENTRYPOINT ["poetry", "run", "ecco"]